### ISSUE TITLE
PA Review: Projects

### ISSUE THREAD

**Issue by trungvuh** [trungvuh/Doable#4]
[ ] Homepage - Projects show
[ ] Project Detail view page
[ ] Create New Project
[ ] Update Own Project
[ ] Delete Project

**Comment by s-pangburn** [comment]
Great job Trung! This project has come a long way, and it looks really adorable 😄 

- [x] Your "Create a Project" button should be in the center of the navbar, not on the bottom.
- [x] Errors on the creation form should be red, and also the padding on top and bottom should be even
- [x] Your form will probably look better if you bring in the margins just a little bit. It's hard to type text going across an entire screen anyway.
- [x] Your images should keep their dimensions without stretching (I can show you how to do this tomorrow)
- [x] Have the "Create Project" and "Cancel" buttons be the same size as the "Upload a Picture" button. Makes it look more unified.
- [x] The image upload dialog should ideally have some indicator of success (even just displaying the state's img_url if successful is okay)
- [ ] On the project index page, the entire div of the project should be a clickable link (this includes title, description text, and so on. Not just the image.
- [x] The text in your Quill text editor should be just a little bit bigger. Let me know if you're having trouble with this and I can help you out.
- [x] Confirm deletion modal needs a little more styling to look more like the rest of the website (use similar colors, make sure the buttons are a similar size and style to those on the form and navbars, etc.)

**Comment by trungvuh** [comment]
Hi Stephen, I fixed all of the issues, except for the clickable link for entire div of the index item. Ideally, I would like it to be clickable on the picture only, since later on I will try to implement user's profile (clickable through user's name), category display (clickable through category), etc. So making the entire div going to the project detail show page is not really ideal. Would that be ok?

**Comment by s-pangburn** [comment]
Sure! But the title should at least be clickable. Once that's done, I will consider this feature complete! Ideally it should underline on hover the way it does on Instructables.

**Comment by trungvuh** [comment]
Oh right. Sure, I fixed that one. Please check them out when you have time. Thanks Stephen!

**Comment by s-pangburn** [comment]
Okay, looks good! I'll mark this as complete 👍  Good work!
